### ISSUE TITLE
Update assets to 3.9.2

### ISSUE THREAD

**Issue by dselivanov** [rstudio/swagger#2]
Hi here. Would be nice to update to latest stable [3.9.2](https://github.com/swagger-api/swagger-ui/tree/v3.9.2) assets which support OpenAPI 3.0 specification.

Obviously I can put new assets into package, but I think it would be great to have them here in one place.

**Comment by dselivanov** [comment]
@javierluraschi CRAN release?

**Comment by javierluraschi** [comment]
It's submitted to CRAN now, should be accepted in a day or two.
