### ISSUE TITLE
How can I use swagger ui?

### ISSUE THREAD

**Issue by kwon14** [rstudio/swagger#22]
Hi. Thank you for your great work!!

I am using R by calling like the following JAVA code.
Recently, swagger was also updated to 3.33.1 to use Plumber 1.0.0, but "{"error":["404-Resource Not Found"]}" occurs.
The server started up normally, but it seems that the UI file could not be found.

Please, Ask for help in this..

Thank U.
-----------------------------------------------------------------------
        String mainCode = "setwd(\'" + targetRepoPath + "/\')" + "\n" +
                "options(plumber.legacyRedirects = FALSE)"+ "\n" +
                "library(plumber)" + "\n" +
                "library(swagger)" + "\n" +
                "convert_empty <- function(string) {\n" +
                "if (string == \"\") { \"-\" } else { string }\n" +
                "}\n" +
                "r <- pr(\'" + filename + "\')" + "\n" +
                "r$registerHooks(\n" +
                "list(\n" +
                "postroute = function(req, res) {\n" +
                "cat(\"[\")\n" +
                "cat(format(Sys.time(), \"%c\"))\n" +
                "cat(\"] \")\n" +
                "cat(paste(convert_empty(req$REMOTE_ADDR), convert_empty(req$HTTP_USER_AGENT), convert_empty(req$HTTP_HOST), convert_empty(req$REQUEST_METHOD), convert_empty(req$PATH_INFO), convert_empty(res$status), sep=\",\"))\n" +
                "cat(\"\\n\")\n" +
                "}))\n" +
                "r %>% pr_set_docs(\"swagger\")" + "\n" +
                "r %>% pr_run(port=" + port + ", host=\'0.0.0.0\')" + "\n\n";

**Comment by meztez** [comment]
@kwon14 There is too much missing here to attempt to answer your question. How can it be reproduced?
