### ISSUE TITLE
[Question] Is it possible to add a login page before Swagger UI?

### ISSUE THREAD

**Issue by jonekeat** [rstudio/swagger#27]
Thanks for creating this amazing package, I really enjoy using it. But I am facing an issue when I try to allow specific users to access the Swagger doc after deployed plumber API.

Is there someway this can be done? I need to dynamically adding/removing user access right

**Comment by meztez** [comment]
@jonekeat It depends a lot on your deployment environment. There are multiple solution that exists to secure your API. None of them would be done with this package as a starting point.

- You could use Posit Connect authentification.
- You could put your API behind a secured proxy.
- You could use a plumber filter.

And many more options.

**Comment by jonekeat** [comment]
how about if we want a login page, with user provide username & password and authenticate to access the swagger doc? 

is it possible to put this login page in Shiny and deploy together with plumber API?

**Comment by meztez** [comment]
@jonekeat I mean, it is possible. But it would not be secure.

Usually, in real world application, the API doc is public, it is the actual endpoints that are secured and required a token. If the actual doc needs to be secured, that would be done at the hosting server level, not within swagger itself.

Do you think the issue could be closed?

You could try to explain what you are trying to achieve on the Posit Community Forum and get help there?
https://community.rstudio.com/

**Comment by jonekeat** [comment]
@meztez Thanks for your explanation! I will close this issue, sorry that I am not very familiar with web technology yet, and posted questions in wrong place
