### ISSUE TITLE
Publishing to CRAN?

### ISSUE THREAD

**Issue by adamrp** [rstudio/swagger#8]
The current version on CRAN is 3.9.2, but this repository shows there have been many new (minor) versions since then.

Are there plans to publish the newer versions to CRAN? And/or, can commits on this repo be tagged with the version number (e.g., so that people's/organizations' RStudio Package Managers' git builders can be triggered when new tagged versions are available)?

**Comment by QuadTriangle** [comment]
@rstudio

**Comment by schloerke** [comment]
Closed 9/14/2020
